### ISSUE TITLE
我这边匹配上了验证码之后post登陆后获取的数据一直是验证码错误

### ISSUE THREAD

**Issue by DevilJessse** [sfl666/cfmmc_spider#1]
我这边匹配上了验证码之后post登陆后获取的数据一直是验证码错误
请问是什么原因导致的呢

**Comment by sfl666** [comment]
识别验证码并不能100%成功,需要多次尝试.
确保账号密码填的没有问题.
可以把res = content2.content.decode()打印出来看看页面有什么提示信息

**Comment by DevilJessse** [comment]
我发现了。是验证码无法匹配上，验证码识别几乎就没有一次是对的。。。请问你有这样的情况吗

**Comment by sfl666** [comment]
我这差不多都能在200次之内匹配上

**Comment by DevilJessse** [comment]
恩恩。我也是偶尔可以匹配上，请问你有研究过如何提高匹配的效率吗？

**Comment by sfl666** [comment]
提高匹配准确率的思路:
1.图片去除噪音 (简单)
2.用大量的期货保证金监控中心的验证码训练tesseract-ocr的模型 (困难)
我觉得你要是爬几个账户的话多匹配几次也用不了多少时间, 你有大量的账户信息要爬的话就并行处理
